### ISSUE TITLE
How do I set the resources requests for worker pod?

### ISSUE THREAD

**Issue by ding-kai** [BrechtDeVlieger/airflow-kube-helm#16]
Hi, I am unable to find the options to set the cpu & memory for worker pod, the default resources is too limited.
```
resources:
  requests:
    cpu: 10m
    memory: 10Mi
```
